### ISSUE TITLE
Jest error

### ISSUE THREAD

**Issue by thorakmedichi** [mmazzarolo/react-native-modal-datetime-picker#482]
Can anyone provide any tips on how to deal with the Jest test errors I am getting?

```js
Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/thorakmedichi/Development/Projects/stormfree/daytracer-updated/node_modules/react-native-modal-datetime-picker/src/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { DateTimePickerModal } from "./DateTimePickerModal";
                                                                                             ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      4 | import { TouchableOpacity, StyleSheet, View, Text } from 'react-native';
      5 | 
    > 6 | import DateTimePicker from 'react-native-modal-datetime-picker';
        | ^
      7 | import InputGroup from './InputGroup';
      8 | 
      9 | // Context

      at Runtime.createScriptFromCode (node_modules/jest-runtime/build/index.js:1266:14)
      at Object.<anonymous> (src/components/inputs/TimeInput.js:6:1)
```

I have the following in my `jest.config.js` file

```js

transformIgnorePatterns: [
        'node_modules/art/core/color.js',
        'node_modules/(?!react-(.*-)?native(-.*)?)',
        'node_modules/react-native-modal-datetime-picker'
    ],
```

**Comment by mmazzarolo** [comment]
👋 @thorakmedichi I think this question is more suited for stackoverflow, (I would also suggest to create a fully reproducible example)

**Comment by HyperNovax** [comment]
I have the same error on my project. I haven't found a solution so far.

**Comment by krifamed** [comment]
You need to also add @react-native-community/datetimepicker to transformIgnorePatterns 
```
 transformIgnorePatterns: [
       // other packages
        'node_modules/react-native-modal-datetime-picker',
        'node_modules/@react-native-community/datetimepicker'
   ],
```
